export interface TabItem {
  name: string
  image: string
  description?: string
}

// Materials
export const materialsData: Record<string, TabItem[]> = {
  'mailer-boxes': [
    { name: 'Card Stock', image: '/images/thumbnail-card-stock.webp', description: 'Thinner and more flexible than corrugated board, card stock is ideal for lightweight products or inserts. Supports high-resolution printing where detail and smoothness are key.' },
    { name: 'Natural Kraft Board', image: '/images/thumbnail-natural-kraft-board.webp', description: 'Made from a mix of virgin and recycled pulp, this unbleached board has a raw, earthy finish. Great for eco-conscious, organic branding.' },
    { name: 'Oyster White Kraft Corrugated', image: '/images/thumbnail-oyster-white-kraft-corrugated.webp', description: 'Smooth, off-white linerboard great for sharp, detailed prints. Offers a subtle background alternative to bright whites.' },
    { name: 'Bleached White Board', image: '/images/thumbnail-bleached-white-corrugated.webp', description: 'Bright, clean, and vivid for high-end printing. Ideal for sharp logos, retail packaging, and attention-grabbing visuals.' },
    { name: 'Kraft', image: '/images/thumbnail-kraft.webp', description: 'Tear-resistant and recyclable brown surface. Best for brands going for a natural, raw, or minimalist style.' },
    { name: 'White Kraft', image: '/images/thumbnail-white-kraft.webp', description: 'Smooth white liner for crisp artwork. Provides a balanced white look without harsh brightness.' },
  ],
  'tuck-boxes': [
    { name: 'Card Stock', image: '/images/thumbnail-card-stock.webp', description: 'Thinner and more flexible than corrugated board, card stock is ideal for lightweight products or inserts. Supports high-resolution printing where detail and smoothness are key.' },
    { name: 'Natural Kraft Board', image: '/images/thumbnail-natural-kraft-board.webp', description: 'Made from a mix of virgin and recycled pulp, this unbleached board has a raw, earthy finish. Great for eco-conscious, organic branding.' },
    { name: 'Oyster White Kraft Corrugated', image: '/images/thumbnail-oyster-white-kraft-corrugated.webp', description: 'Smooth, off-white linerboard great for sharp, detailed prints. Offers a subtle background alternative to bright whites.' },
    { name: 'Bleached White Board', image: '/images/thumbnail-bleached-white-corrugated.webp', description: 'Bright, clean, and vivid for high-end printing. Ideal for sharp logos, retail packaging, and attention-grabbing visuals.' },
    { name: 'Kraft', image: '/images/thumbnail-kraft.webp', description: 'Tear-resistant and recyclable brown surface. Best for brands going for a natural, raw, or minimalist style.' },
    { name: 'White Kraft', image: '/images/thumbnail-white-kraft.webp', description: 'Smooth white liner for crisp artwork. Provides a balanced white look without harsh brightness.' },
  ],
  'rigid-boxes': [
    { name: 'Grey Chipboard', image: '/images/thumbnail-grey-chipboard.webp', description: 'Uncoated material that is thick, durable, and eco-friendly used as the base material for custom rigid boxes for a premium construction.' },
    { name: 'Card Stock', image: '/images/thumbnail-card-stock%20(1).webp', description: 'Premium material with a smooth surface often used as inner liners or printed wraps for rigid boxes, promising excellent print quality. Ideal for high-resolution graphics and finishes like foil stamping or UV coating.' },
    { name: 'Black Kraft', image: '/images/thumbnail-black-kraft.webp', description: 'Great for luxury or eco-friendly packaging. Its deep color eliminates the need for excessive ink coverage and adds a sleek and minimal appeal. Often used in high-end sustainable product packaging.' },
    { name: 'Holographic', image: '/images/thumbnail-holographic.webp', description: 'Specialty paper used as an outer wrap for creating a striking, eye-catching rainbow effect. Popular in cosmetics, tech gadgets, and promotional packaging that needs to stand out on shelves.' },
    { name: 'Natural Brown Kraft', image: '/images/thumbnail-kraft%20(1).webp', description: 'Popular with eco-conscious brands and organic product packaging. This material offers a rustic, earthy look. Often used without lamination to highlight its natural porous texture.' },
    { name: 'Metallic', image: '/images/thumbnail-metallic.webp', description: 'Ideal for luxury and festive packaging, such as for cosmetics, perfumes, or seasonal gift boxes. This specialty paper comes with a glossy or matte metallic finish that adds a premium and celebratory feel.' },
    { name: 'White Kraft', image: '/images/thumbnail-white-kraft%20(1).webp', description: 'A perfect blend between a clean, natural look and the strength of kraft. White Kraft is often used where brands want an eco-friendly appearance but with a bright, printable surface.' },
    { name: 'Textured', image: '/images/thumbnail-textured-linen.webp', description: 'Primarily used for outer wraps to provide a tactile, upscale experience. This specialty paper is common in premium retail packaging, jewelry boxes, and high-end electronics packaging.' },
  ],
  'dispenser-boxes': [
    { name: 'White', image: '/images/cardboard-paper.webp', description: 'A smooth, bright white paperboard that offers a clean and professional appearance. Ideal for high-quality printing, vibrant colors, and detailed graphics. Commonly used for retail and custom packaging where a crisp, premium finish is desired.' },
    { name: 'Card Stock', image: '/images/64560be3b9c3f71ff4381e26-20sheets-glitter-cardstock-paper-10.webp', description: 'high-quality paper material used in premium packaging for its smooth finish, excellent printability, and structural integrity. Available in various finishes such as gloss, matte, or uncoated, it offers a clean look and can be easily customized with vibrant colors, foil stamping, embossing, or coatings—making it ideal for retail boxes, cosmetics, and branded packaging.' },
    { name: 'Corrugated', image: '/images/what-is-corrugated-packaging-1.webp', description: 'Fluted inner layer sandwiched between two flat linerboards, offering superior strength, cushioning, and durability. Ideal for shipping, storage, and heavy-duty packaging, it protects products during transit while allowing for full customization with prints, coatings, and branding. Widely used in e-commerce, retail, and industrial packaging for its cost-effectiveness and reliability.' },
    { name: 'Foil', image: '/images/7-411.webp', description: 'Foil is a luxurious metallic finish applied to packaging surfaces to enhance visual appeal and highlight specific design elements. Available in various shades like gold, silver, rose gold, and holographic, foil stamping adds a reflective, high-end touch to logos, text, or patterns—making packaging look premium, elegant, and attention-grabbing.' },
    { name: 'Kraft', image: '/images/istockphoto-1375373998-612x612.webp', description: 'Eco-friendly packaging material made from recycled paper with a natural brown finish. Known for its strength and rustic appeal, it’s ideal for brands focused on sustainability and minimalism. Kraft is fully recyclable, biodegradable, and can be customized with simple or bold designs using eco-friendly inks.' },
    { name: 'Rigid', image: '/images/Duplex-Board.webp', description: 'Thick paperboard known for its superior durability, structure, and luxurious feel. Commonly used for high-end packaging like gift boxes, electronics, cosmetics, and luxury goods, rigid boxes offer a solid, non-collapsible form that enhances product value and creates a memorable unboxing experience. Ideal for custom finishes such as embossing, foil stamping, magnetic closures, and fabric linings.' },
  ],
  'magnetic-closure': [
    { name: 'White', image: '/images/cardboard-paper.webp', description: 'A smooth, bright white paperboard that offers a clean and professional appearance. Ideal for high-quality printing, vibrant colors, and detailed graphics. Commonly used for retail and custom packaging where a crisp, premium finish is desired.' },
    { name: 'Card Stock', image: '/images/64560be3b9c3f71ff4381e26-20sheets-glitter-cardstock-paper-10.webp', description: 'high-quality paper material used in premium packaging for its smooth finish, excellent printability, and structural integrity. Available in various finishes such as gloss, matte, or uncoated, it offers a clean look and can be easily customized with vibrant colors, foil stamping, embossing, or coatings—making it ideal for retail boxes, cosmetics, and branded packaging.' },
    { name: 'Corrugated', image: '/images/what-is-corrugated-packaging-1.webp', description: 'Fluted inner layer sandwiched between two flat linerboards, offering superior strength, cushioning, and durability. Ideal for shipping, storage, and heavy-duty packaging, it protects products during transit while allowing for full customization with prints, coatings, and branding. Widely used in e-commerce, retail, and industrial packaging for its cost-effectiveness and reliability.' },
    { name: 'Foil', image: '/images/7-411.webp', description: 'Foil is a luxurious metallic finish applied to packaging surfaces to enhance visual appeal and highlight specific design elements. Available in various shades like gold, silver, rose gold, and holographic, foil stamping adds a reflective, high-end touch to logos, text, or patterns—making packaging look premium, elegant, and attention-grabbing.' },
    { name: 'Kraft', image: '/images/istockphoto-1375373998-612x612.webp', description: 'Eco-friendly packaging material made from recycled paper with a natural brown finish. Known for its strength and rustic appeal, it’s ideal for brands focused on sustainability and minimalism. Kraft is fully recyclable, biodegradable, and can be customized with simple or bold designs using eco-friendly inks.' },
    { name: 'Rigid', image: '/images/Duplex-Board.webp', description: 'Thick paperboard known for its superior durability, structure, and luxurious feel. Commonly used for high-end packaging like gift boxes, electronics, cosmetics, and luxury goods, rigid boxes offer a solid, non-collapsible form that enhances product value and creates a memorable unboxing experience. Ideal for custom finishes such as embossing, foil stamping, magnetic closures, and fabric linings.' },
  ],
}

// Printing
export const printingData: Record<string, TabItem[]> = {
  'mailer-boxes': [
    { name: 'Digital Printing', image: '/images/bf037986cf978e92147a49d08bdad316_larger_format_p.webp', description: 'High-end printing technique ideal for high-volume runs with consistent color and sharp detail. Great for premium packaging where precise branding is key for a large volume of boxes.' },
    { name: 'Digital Print', image: '/images/MGAUKXTXQRVQIAQVVUIEYBWQ6W3U09799.webp', description: 'Best for short runs or personalized packaging, where printing speed is your concern. This technique offers a quick turnaround and is cost-effective for small batches or packaging prototypes.' },
    { name: 'Water-base Ink', image: '/images/Water-based-screen-printing-inks-for-fabrics.webp', description: 'Eco-friendly ink option for printing, suitable for brands focusing on sustainability. Offers good print quality and sharp results with less environmental impact.' },
    { name: 'Soy / Vegetable Ink', image: '/images/images%20(1).webp', description: 'Another eco-conscious choice that provides vibrant colors and is easier to remove during recycling. This option is highly preferred by sustainable brands and is great for organic or green product lines.' },
    { name: 'Pantone', image: '/images/GP6102B-Pantone-Color-Bridge-Guide-Set-5_web-740x450.webp', description: 'Exceptional color model perfect for brand-specific colors. Ensures that logos, icons, and key elements look exactly the same on every box. Great to use when accurate branding holds the utmost importance.' },
    { name: 'Pantone Metallic', image: '/images/PANTONE_877_vs_PANTONE_Silver_10077_C.webp', description: 'A premium color model that adds luxury and shimmer to packaging. This method is common in cosmetics, perfumes, and premium gifts to enhance shelf appeal by offering a top-of-the-line feel with the colors.' },
  ],
  'tuck-boxes':[
    { name: 'Digital Printing', image: '/images/bf037986cf978e92147a49d08bdad316_larger_format_p.webp', description: 'High-end printing technique ideal for high-volume runs with consistent color and sharp detail. Great for premium packaging where precise branding is key for a large volume of boxes.' },
    { name: 'Digital Print', image: '/images/MGAUKXTXQRVQIAQVVUIEYBWQ6W3U09799.webp', description: 'Best for short runs or personalized packaging, where printing speed is your concern. This technique offers a quick turnaround and is cost-effective for small batches or packaging prototypes.' },
    { name: 'Water-base Ink', image: '/images/Water-based-screen-printing-inks-for-fabrics.webp', description: 'Eco-friendly ink option for printing, suitable for brands focusing on sustainability. Offers good print quality and sharp results with less environmental impact.' },
    { name: 'Soy / Vegetable Ink', image: '/images/images%20(1).webp', description: 'Another eco-conscious choice that provides vibrant colors and is easier to remove during recycling. This option is highly preferred by sustainable brands and is great for organic or green product lines.' },
    { name: 'Pantone', image: '/images/GP6102B-Pantone-Color-Bridge-Guide-Set-5_web-740x450.webp', description: 'Exceptional color model perfect for brand-specific colors. Ensures that logos, icons, and key elements look exactly the same on every box. Great to use when accurate branding holds the utmost importance.' },
    { name: 'Pantone Metallic', image: '/images/PANTONE_877_vs_PANTONE_Silver_10077_C.webp', description: 'A premium color model that adds luxury and shimmer to packaging. This method is common in cosmetics, perfumes, and premium gifts to enhance shelf appeal by offering a top-of-the-line feel with the colors.' },
  ],
  'rigid-boxes': [
    { name: 'Digital Printing', image: '/images/bf037986cf978e92147a49d08bdad316_larger_format_p.webp', description: 'High-end printing technique ideal for high-volume runs with consistent color and sharp detail. Great for premium packaging where precise branding is key for a large volume of boxes.' },
    { name: 'Digital Print', image: '/images/MGAUKXTXQRVQIAQVVUIEYBWQ6W3U09799.webp', description: 'Best for short runs or personalized packaging, where printing speed is your concern. This technique offers a quick turnaround and is cost-effective for small batches or packaging prototypes.' },
    { name: 'Water-base Ink', image: '/images/Water-based-screen-printing-inks-for-fabrics.webp', description: 'Eco-friendly ink option for printing, suitable for brands focusing on sustainability. Offers good print quality and sharp results with less environmental impact.' },
    { name: 'Soy / Vegetable Ink', image: '/images/images%20(1).webp', description: 'Another eco-conscious choice that provides vibrant colors and is easier to remove during recycling. This option is highly preferred by sustainable brands and is great for organic or green product lines.' },
    { name: 'Pantone', image: '/images/GP6102B-Pantone-Color-Bridge-Guide-Set-5_web-740x450.webp', description: 'Exceptional color model perfect for brand-specific colors. Ensures that logos, icons, and key elements look exactly the same on every box. Great to use when accurate branding holds the utmost importance.' },
    { name: 'Pantone Metallic', image: '/images/PANTONE_877_vs_PANTONE_Silver_10077_C.webp', description: 'A premium color model that adds luxury and shimmer to packaging. This method is common in cosmetics, perfumes, and premium gifts to enhance shelf appeal by offering a top-of-the-line feel with the colors.' },
  ],
  'dispenser-boxes': [
    { name: 'Digital Printing', image: '/images/bf037986cf978e92147a49d08bdad316_larger_format_p.webp', description: 'High-end printing technique ideal for high-volume runs with consistent color and sharp detail. Great for premium packaging where precise branding is key for a large volume of boxes.' },
    { name: 'Digital Print', image: '/images/MGAUKXTXQRVQIAQVVUIEYBWQ6W3U09799.webp', description: 'Best for short runs or personalized packaging, where printing speed is your concern. This technique offers a quick turnaround and is cost-effective for small batches or packaging prototypes.' },
    { name: 'Water-base Ink', image: '/images/Water-based-screen-printing-inks-for-fabrics.webp', description: 'Eco-friendly ink option for printing, suitable for brands focusing on sustainability. Offers good print quality and sharp results with less environmental impact.' },
    { name: 'Soy / Vegetable Ink', image: '/images/images%20(1).webp', description: 'Another eco-conscious choice that provides vibrant colors and is easier to remove during recycling. This option is highly preferred by sustainable brands and is great for organic or green product lines.' },
    { name: 'Pantone', image: '/images/GP6102B-Pantone-Color-Bridge-Guide-Set-5_web-740x450.webp', description: 'Exceptional color model perfect for brand-specific colors. Ensures that logos, icons, and key elements look exactly the same on every box. Great to use when accurate branding holds the utmost importance.' },
    { name: 'Pantone Metallic', image: '/images/PANTONE_877_vs_PANTONE_Silver_10077_C.webp', description: 'A premium color model that adds luxury and shimmer to packaging. This method is common in cosmetics, perfumes, and premium gifts to enhance shelf appeal by offering a top-of-the-line feel with the colors.' },
  ],
  'magnetic-closure': [
    { name: 'Digital Printing', image: '/images/bf037986cf978e92147a49d08bdad316_larger_format_p.webp', description: 'High-end printing technique ideal for high-volume runs with consistent color and sharp detail. Great for premium packaging where precise branding is key for a large volume of boxes.' },
    { name: 'Digital Print', image: '/images/MGAUKXTXQRVQIAQVVUIEYBWQ6W3U09799.webp', description: 'Best for short runs or personalized packaging, where printing speed is your concern. This technique offers a quick turnaround and is cost-effective for small batches or packaging prototypes.' },
    { name: 'Water-base Ink', image: '/images/Water-based-screen-printing-inks-for-fabrics.webp', description: 'Eco-friendly ink option for printing, suitable for brands focusing on sustainability. Offers good print quality and sharp results with less environmental impact.' },
    { name: 'Soy / Vegetable Ink', image: '/images/images%20(1).webp', description: 'Another eco-conscious choice that provides vibrant colors and is easier to remove during recycling. This option is highly preferred by sustainable brands and is great for organic or green product lines.' },
    { name: 'Pantone', image: '/images/GP6102B-Pantone-Color-Bridge-Guide-Set-5_web-740x450.webp', description: 'Exceptional color model perfect for brand-specific colors. Ensures that logos, icons, and key elements look exactly the same on every box. Great to use when accurate branding holds the utmost importance.' },
    { name: 'Pantone Metallic', image: '/images/PANTONE_877_vs_PANTONE_Silver_10077_C.webp', description: 'A premium color model that adds luxury and shimmer to packaging. This method is common in cosmetics, perfumes, and premium gifts to enhance shelf appeal by offering a top-of-the-line feel with the colors.' },
  ],
}

// Finishes
export const finishesData: Record<string, TabItem[]> = {
  'mailer-boxes': [
    { name: 'Aqueous Coating', image: '/images/thumbnail-aqueous-coating.webp', description: 'A fast-drying, water-based finish that adds light protection and a clean surface feel. Available in gloss or matte, this eco-friendly coating is ideal for print-heavy boxes and helps resist fingerprints and minor scuffs.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-soft-touch-coating.webp', description: 'Adds a velvet-like texture to your packaging, creating a soft, matte surface that feels premium in hand. Ideal for brands that want a more tactile, elegant unboxing experience without shine or glare.' },
    { name: 'Varnish', image: '/images/thumbnail-varnish.webp', description: 'A clear coating that adds shine, smoothness, and print protection. Applied using CMYK presses and available in gloss, satin, or matte finishes. Best for enhancing colors while keeping costs low.' },
    { name: 'Spot Gloss UV', image: '/images/thumbnail-spot-gloss-uv.webp', description: 'Gloss coating applied to select areas of the print, adding contrast and focus. Often used on logos or text to create shine that stands out against a matte background. UV cured for durability.' },
    { name: 'Lamination', image: '/images/thumbnail-lamination.webp', description: 'A thin film layered over the surface of the box to increase durability and moisture resistance. Ideal for protecting full-color designs and maintaining box integrity during shipping or retail handling.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-anti-scratch-lamination.webp', description: 'BOPP (biaxially oriented polypropylene) lamination that resists scuffs, scratches, and fingerprints. Provides a smooth finish with added protection for heavily handled boxes.' },
  ],
  'tuck-boxes': [
    { name: 'Aqueous Coating', image: '/images/thumbnail-aqueous-coating.webp', description: 'A fast-drying, water-based finish that adds light protection and a clean surface feel. Available in gloss or matte, this eco-friendly coating is ideal for print-heavy boxes and helps resist fingerprints and minor scuffs.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-soft-touch-coating.webp', description: 'Adds a velvet-like texture to your packaging, creating a soft, matte surface that feels premium in hand. Ideal for brands that want a more tactile, elegant unboxing experience without shine or glare.' },
    { name: 'Varnish', image: '/images/thumbnail-varnish.webp', description: 'A clear coating that adds shine, smoothness, and print protection. Applied using CMYK presses and available in gloss, satin, or matte finishes. Best for enhancing colors while keeping costs low.' },
    { name: 'Spot Gloss UV', image: '/images/thumbnail-spot-gloss-uv.webp', description: 'Gloss coating applied to select areas of the print, adding contrast and focus. Often used on logos or text to create shine that stands out against a matte background. UV cured for durability.' },
    { name: 'Lamination', image: '/images/thumbnail-lamination.webp', description: 'A thin film layered over the surface of the box to increase durability and moisture resistance. Ideal for protecting full-color designs and maintaining box integrity during shipping or retail handling.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-anti-scratch-lamination.webp', description: 'BOPP (biaxially oriented polypropylene) lamination that resists scuffs, scratches, and fingerprints. Provides a smooth finish with added protection for heavily handled boxes.' },
  ],
  'rigid-boxes': [
    { name: 'Aqueous Coating', image: '/images/thumbnail-aqua-coating.webp', description: 'Add a waterproof layer to your packaging with aqueous coating. This coating method prevents your packaging from moisture damage and also smudges and fingerprints. Use this to maintain the luxury appeal and shiny look of your boxes.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-soft-touch-coating%20(1).webp', description: 'Best to use when you need to highlight specific elements on your packaging. This coating method adds a shiny or dull effect to any select design element on your packaging, such as the logo, an image, text, or anything else.' },
    { name: 'Varnish', image: '/images/thumbnail-varnish%20(1).webp', description: 'Add an extra layer of protection to the surface of your custom rigid boxes. You can go for various varnish options such as gloss varnish, matte varnish, silk varnish, and spot varnish. They offer extra protection while enhancing the visual appeal of your boxes.' },
    { name: 'Spot Gloss UV', image: '/images/thumbnail-spot-uv-gloss.webp', description: 'Add a shiny UV effect to a specific area or an element on your rigid boxes. This technique is best when you wish to highlight specific elements such as a logo, text, image, or anything else.' },
    { name: 'Lamination', image: '/images/thumbnail-lamination%20(1).webp', description: 'Best for adding a protective film to your boxes. Laminated rigid boxes for retail are a great idea as they offer a premium look. You can choose from gloss and matte lamination as per your branding demands and the product’s vibe. It not only protects the packaging surface but also adds an eye-catching appeal.' },
    { name: 'Anti-scratch Lamination', image: '/images/thumbnail-anti-scratch-lamination%20(1).webp', description: 'Protect your packaging boxes against scratches using this lamination technique. It is excellent to keep your boxes always looking like new, no matter how long they stay on the store shelves or with the customer.' },
    { name: 'Soft Touch / Silk Lamination', image: '/images/thumbnail-soft-touch-coating%20(1).webp', description: 'Don’t just capture the eye when you can also capture the touch. This lamination technique offers a multi-sensory experience by offering a silk-like feel to the touch, which can capture more attention. It can be applied to the entire box or a specific element.' },
    { name: 'Matte Lamination', image: '/images/thumbnail-matt-lamination.webp', description: 'For a premium and sleek appearance, we offer matte lamination that adds a dull yet elegant look to your packaging boxes. Best for use with premium or luxury product packaging, such as limited edition items or gifts.' },
  ],
  'dispenser-boxes': [
    { name: 'Aqueous Coating', image: '/images/thumbnail-aqueous-coating.webp', description: 'A fast-drying, water-based finish that adds light protection and a clean surface feel. Available in gloss or matte, this eco-friendly coating is ideal for print-heavy boxes and helps resist fingerprints and minor scuffs.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-soft-touch-coating.webp', description: 'Adds a velvet-like texture to your packaging, creating a soft, matte surface that feels premium in hand. Ideal for brands that want a more tactile, elegant unboxing experience without shine or glare.' },
    { name: 'Varnish', image: '/images/thumbnail-varnish.webp', description: 'A clear coating that adds shine, smoothness, and print protection. Applied using CMYK presses and available in gloss, satin, or matte finishes. Best for enhancing colors while keeping costs low.' },
    { name: 'Spot Gloss UV', image: '/images/thumbnail-spot-gloss-uv.webp', description: 'Gloss coating applied to select areas of the print, adding contrast and focus. Often used on logos or text to create shine that stands out against a matte background. UV cured for durability.' },
    { name: 'Lamination', image: '/images/thumbnail-lamination.webp', description: 'A thin film layered over the surface of the box to increase durability and moisture resistance. Ideal for protecting full-color designs and maintaining box integrity during shipping or retail handling.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-anti-scratch-lamination.webp', description: 'BOPP (biaxially oriented polypropylene) lamination that resists scuffs, scratches, and fingerprints. Provides a smooth finish with added protection for heavily handled boxes.' },
  ],
  'magnetic-closure': [
    { name: 'Aqueous Coating', image: '/images/thumbnail-aqueous-coating.webp', description: 'A fast-drying, water-based finish that adds light protection and a clean surface feel. Available in gloss or matte, this eco-friendly coating is ideal for print-heavy boxes and helps resist fingerprints and minor scuffs.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-soft-touch-coating.webp', description: 'Adds a velvet-like texture to your packaging, creating a soft, matte surface that feels premium in hand. Ideal for brands that want a more tactile, elegant unboxing experience without shine or glare.' },
    { name: 'Varnish', image: '/images/thumbnail-varnish.webp', description: 'A clear coating that adds shine, smoothness, and print protection. Applied using CMYK presses and available in gloss, satin, or matte finishes. Best for enhancing colors while keeping costs low.' },
    { name: 'Spot Gloss UV', image: '/images/thumbnail-spot-gloss-uv.webp', description: 'Gloss coating applied to select areas of the print, adding contrast and focus. Often used on logos or text to create shine that stands out against a matte background. UV cured for durability.' },
    { name: 'Lamination', image: '/images/thumbnail-lamination.webp', description: 'A thin film layered over the surface of the box to increase durability and moisture resistance. Ideal for protecting full-color designs and maintaining box integrity during shipping or retail handling.' },
    { name: 'Soft Touch Coating', image: '/images/thumbnail-anti-scratch-lamination.webp', description: 'BOPP (biaxially oriented polypropylene) lamination that resists scuffs, scratches, and fingerprints. Provides a smooth finish with added protection for heavily handled boxes.' },
  ],
}

// Box Styles
export const boxStylesData: Record<string, TabItem[]> = {
  'mailer-boxes': [
    { name: 'Roll Ends With Lid (C005)', image: '/images/thumbnail-roll-end-with-lid.webp', description: 'Thinner and more flexible than corrugated board, card stock is ideal for lightweight products or inserts. Supports high-resolution printing where detail and smoothness are key.' },
    { name: 'Roll End Tuck Front Corrugated Box (C003)', image: '/images/thumbnail-roll-end-tuck-front-corrugated-box.webp', description: 'Made from a mix of virgin and recycled pulp, this unbleached board has a raw, earthy finish. Great for eco-conscious, organic branding.' },
    { name: 'Roll End Tuck Top Corrugated Box (C002)', image: '/images/thumbnail-roll-end-tuck-top-corrugated-box.webp', description: 'Smooth, off-white linerboard great for sharp, detailed prints. Offers a subtle background alternative to bright whites.' },
    { name: 'Roll End 3 Flap Lock Corrugated Box (C004)', image: '/images/thumbnail-roll-end-3-flap-lock-corrugated.webp', description: 'Bright, clean, and vivid for high-end printing. Ideal for sharp logos, retail packaging, and attention-grabbing visuals.' },
  ],
  'tuck-boxes': [
    { name: 'Roll Ends With Lid (C005)', image: '/images/thumbnail-roll-end-with-lid.webp', description: 'Thinner and more flexible than corrugated board, card stock is ideal for lightweight products or inserts. Supports high-resolution printing where detail and smoothness are key.' },
    { name: 'Roll End Tuck Front Corrugated Box (C003)', image: '/images/thumbnail-roll-end-tuck-front-corrugated-box.webp', description: 'Made from a mix of virgin and recycled pulp, this unbleached board has a raw, earthy finish. Great for eco-conscious, organic branding.' },
    { name: 'Roll End Tuck Top Corrugated Box (C002)', image: '/images/thumbnail-roll-end-tuck-top-corrugated-box.webp', description: 'Smooth, off-white linerboard great for sharp, detailed prints. Offers a subtle background alternative to bright whites.' },
    { name: 'Roll End 3 Flap Lock Corrugated Box (C004)', image: '/images/thumbnail-roll-end-3-flap-lock-corrugated.webp', description: 'Bright, clean, and vivid for high-end printing. Ideal for sharp logos, retail packaging, and attention-grabbing visuals.' },
  ],
  'rigid-boxes': [
    { name: 'Magnetic Closure Boxes', image: '/images/thumbnail-magnetic-closure.webp', description: 'Offer a premium unboxing experience to your customers by using a magnetic closure. These boxes feature a unique feel when they are opened, making your product memorable.' },
    { name: 'Collapsible / Foldable Boxes', image: '/images/thumbnail-collapsible-foldable.webp', description: 'Save storage space with collapsible boxes. These boxes can easily be ordered in bulk as they are shipped flat, saving money on shipping costs. They are also easy to assemble, making product packaging faster.' },
    { name: 'Lift-Off / Detachable Lid', image: '/images/thumbnail-liftoff-detachable-lid.webp', description: 'Also known as a two-piece box, these boxes feature a removable lid for a gift-like unboxing. Best for premium gift packaging for various products like jewelry, watches, high-end electronics, and more.' },
    { name: 'Shoulder / Neck', image: '/images/thumbnail-shoulder-neck.webp', description: 'This style comes with a detachable lid that stylishly closes on the base while showing a visible border (“the neck”). Best for luxury product packaging used especially for apparel, jewelry, and other products.' },
    { name: 'Sleeve and Tray', image: '/images/thumbnail-match-slide.webp', description: 'Featuring a match-box-like unboxing, this box is a popular style for rigid boxes. You can also add an insert to make them even more premium. Best to use for packing candles, CBD tinctures, and other products.' },
  ],
  'dispenser-boxes': [
    { name: 'Roll Ends With Lid (C005)', image: '/images/thumbnail-roll-end-with-lid.webp', description: 'Thinner and more flexible than corrugated board, card stock is ideal for lightweight products or inserts. Supports high-resolution printing where detail and smoothness are key.' },
    { name: 'Roll End Tuck Front Corrugated Box (C003)', image: '/images/thumbnail-roll-end-tuck-front-corrugated-box.webp', description: 'Made from a mix of virgin and recycled pulp, this unbleached board has a raw, earthy finish. Great for eco-conscious, organic branding.' },
    { name: 'Roll End Tuck Top Corrugated Box (C002)', image: '/images/thumbnail-roll-end-tuck-top-corrugated-box.webp', description: 'Smooth, off-white linerboard great for sharp, detailed prints. Offers a subtle background alternative to bright whites.' },
    { name: 'Roll End 3 Flap Lock Corrugated Box (C004)', image: '/images/thumbnail-roll-end-3-flap-lock-corrugated.webp', description: 'Bright, clean, and vivid for high-end printing. Ideal for sharp logos, retail packaging, and attention-grabbing visuals.' },
  ],
   'magnetic-closure': [
    { name: 'Roll Ends With Lid (C005)', image: '/images/thumbnail-roll-end-with-lid.webp', description: 'Thinner and more flexible than corrugated board, card stock is ideal for lightweight products or inserts. Supports high-resolution printing where detail and smoothness are key.' },
    { name: 'Roll End Tuck Front Corrugated Box (C003)', image: '/images/thumbnail-roll-end-tuck-front-corrugated-box.webp', description: 'Made from a mix of virgin and recycled pulp, this unbleached board has a raw, earthy finish. Great for eco-conscious, organic branding.' },
    { name: 'Roll End Tuck Top Corrugated Box (C002)', image: '/images/thumbnail-roll-end-tuck-top-corrugated-box.webp', description: 'Smooth, off-white linerboard great for sharp, detailed prints. Offers a subtle background alternative to bright whites.' },
    { name: 'Roll End 3 Flap Lock Corrugated Box (C004)', image: '/images/thumbnail-roll-end-3-flap-lock-corrugated.webp', description: 'Bright, clean, and vivid for high-end printing. Ideal for sharp logos, retail packaging, and attention-grabbing visuals.' },
  ],
}
